import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p className={styles.description}>
					Learn coding by doing{' '}
					<code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					<Link href='/learn/nextjs' className={styles.card}>
						<h2>NextJs &rarr;</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</Link>

					<Link href='/learn/react' className={styles.card}>
						<h2>React &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</Link>

					<Link href='/learn/vue' className={styles.card}>
						<h2>Vue &rarr;</h2>
						<p>Learn Vue.js in an interactive course with quizzes!</p>
					</Link>

					<Link href='/learn/angular' className={styles.card}>
						<h2>Angular &rarr;</h2>
						<p>Learn Angular in an interactive course with quizzes!</p>
					</Link>

					<Link href='/contacts' className={styles.card}>
						<h2>Challenge 01 &rarr;</h2>
						<p>This challenge is about dynamic routing.</p>
					</Link>

					<a
						href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						className={styles.card}
					>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
